version: "3.9"

services:
  app:
    container_name: project_template
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8020:8000"
    restart: on-failure
    volumes:
      - ./app/:/app/app/
      - ./tests/:/app/tests/
    environment:
      - DATABASE_URL=postgresql://user:secret@db:5432/db_name
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:14.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=db_name

volumes:
  postgres_data:
