"""Typings for queries generated by aiosql"""

from typing import Dict, Literal, Optional, Sequence

from asyncpg import Connection, Record

# class ExampleQueriesMixin:
#     async def get_user_by_email(self, conn: Connection, *, email: str) -> Record: ...


class Queries(
    # ExampleQueriesMixin,
): ...

queries: Queries
